name: SEC Scraper
on:
  schedule:
    - cron: '*/10 10-23 * * 1-5'  # 10 AM to 11 PM UTC
    - cron: '*/10 0-2 * * 2-6'     # 12 AM to 2 AM UTC (next day)
  workflow_dispatch:  # Allow manual triggers
jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - run: python sec_scraper.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
